openapi: 3.0.1
info:
  title: FOM-OCM-API
  description: An api to obtain information about a order change matrix based on request parameters
  contact:
    name: Fulfilment-Order-Management-Team
    url: https://confluence.build.ingka.ikea.com/display/SOF/FOM+%3A+Team
    email: dl.om.fom.gl@ingka.com
  version: 0.0.3
externalDocs:
  description: Documentation Order Change Matrix Service
  url: https://confluence.build.ingka.ikea.com/pages/viewpage.action?spaceKey=SOF&title=OCM+clarifications
servers:
  - url: http://localhost:8080
    description: Local
  - url: https://api.ingka.dev.ikeadt.com/fom
    description: Dev Server
  - url: https://api.ingka.ppe.ikeadt.com/fom
    description: Stage Server
  - url: https://api.ingka.ikeadt.com/fom
    description: Production Server
paths:
  /ocm/{countryCode}/{services}:
    get:
      tags:
        - ocm-controller
      operationId: getOcmList
      parameters:
        - name: countryCode
          in: path
          required: true
          schema:
            type: string
        - name: services
          in: path
          required: true
          schema:
            type: array
            items:
              type: string
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/OcmResponse'
  /allowed-modifications:
    post:
      summary: "POST endpoint used for getting list of allowed-modifications"
      operationId: "getAllowedModifications"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/AllowedModificationsRequest"
        required: true
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/AllowedModificationsResponse"
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Bad request
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Internal server error


components:
  schemas:
    ErrorResponse:
      type: object
      description: API Error Response Model for Ingka Business Web API
      externalDocs:
        description: Ingka ProblemJSON definition
        url: https://github.com/ingka-group-digital/api-standards/blob/main/docs/WebAPI/resources/template/ProblemJSONTemplate.yaml
      properties:
        detail:
          type: string
          description: A human readable explanation specific to this occurrence of
            the problem
          example: Connection to database timed out
        status:
          type: integer
          format: int32
          description: The HTTP status code generated by the origin server for this
            occurrence of the problem
          example: 503
          exclusiveMaximum: true
          maximum: 600
          minimum: 100
        title:
          type: string
          description: "A short, summary of the problem type, readable for engineers"
          example: Service Unavailable
        type:
          type: string
          format: uri
          default: about:blank
          description: An absolute URI that identifies the problem type
          example: https://api.ingka.ikea.com/problem/constraint-violation
    OcmEntryResponse:
      required:
        - allowed
        - modificationType
      type: object
      properties:
        modificationType:
          type: string
        allowed:
          type: string
    OcmResponse:
      required:
        - deliveryRules
        - lineRules
        - orderRules
        - service
      type: object
      properties:
        service:
          type: string
        orderRules:
          type: object
          additionalProperties:
            type: array
            items:
              $ref: '#/components/schemas/OcmEntryResponse'
        lineRules:
          type: object
          additionalProperties:
            type: array
            items:
              $ref: '#/components/schemas/OcmEntryResponse'
        deliveryRules:
          type: object
          additionalProperties:
            type: array
            items:
              $ref: '#/components/schemas/OcmEntryResponse'
    AllowedModificationsRequest:
      type: "object"
      properties:
        orderStatus:
          type: "string"
        processType:
          type: "string"
        userRole:
          type: "string"
        serviceType:
          type: "string"
        transportMethod:
          type: "string"
        orgCode:
          type: "string"
        storeFulfillment:
          type: "boolean"
    AllowedModificationsResponse:
      type: "object"
      properties:
        allowedModifications:
          type: "array"
          items:
            type: "string"